language: python # => 1

python: # => 2

  - "3.5"

services: # => 3

env: # => 4

  -DJANGO=1.11 DB=sqlite3
install: # => 5

  - pip install -r requirements.txt

before_script: # => 6

script: # => 7

  - python manage.py test
